import cors from "cors";
import express from "express";
import helmet from "helmet";
import { env } from "./config.js";
import { authenticate } from "./auth.js";
import { usersRouter } from "./users.js";
import { configurationRouter } from "./configuration.js";
import { crmRouter } from "./crm.js";
import type { AuthedRequest } from "./types.js";

const app = express();
app.use(helmet());
app.use(cors({ origin: ["http://localhost:5173"], credentials: true }));
app.use(express.json({ limit: "8mb" }));
app.get("/api/health", (_req, res) => res.json({ status: "ok" }));
app.get("/api/me", authenticate as never, (req: any, res) => res.json(req.appUser));
app.use("/api/users", usersRouter);
app.use("/api/configuration", configurationRouter);
app.use("/api/crm", crmRouter);
app.use((_req, res) => res.status(404).json({ error: "Rota não encontrada." }));
app.listen(env.PORT, () => console.log(`EduClick API on :${env.PORT}`));
