import { useEffect, useState } from "react";
import { Check, Clock3, KeyRound, Lock, Palette, Plus, Save, Settings2, Tags, Trash2, Upload, UserCog, Users, Wifi } from "lucide-react";
import { Badge, PageHead } from "../components";
import { api, roleLabel, type Profile, type Role } from "../lib";
import { useAuth } from "../auth";
const tabs=[["criar","Criar usuário",Plus],["usuarios","Gerenciar usuários",Users],["etiquetas","Etiquetas",Tags],["pipeline","Etapas do pipeline",Settings2],["fila","Fila de atendimento",Clock3],["credenciais","Credenciais",KeyRound],["aparencia","Aparência",Palette]] as const;
export function Settings(){const {profile}=useAuth();const [tab,setTab]=useState("criar");const visible=tabs.filter(t=>!["credenciais","aparencia"].includes(t[0])||profile?.role==="admin_master");
return <><PageHead title="Configurações" subtitle="Personalize usuários, operação e integrações."/ ><div className="settings-layout"><aside className="settings-nav">{visible.map(([id,l,I])=><button className={tab===id?"active":""} onClick={()=>setTab(id)} key={id}><I/>{l}</button>)}</aside><section className="card settings-content">{tab==="criar"?<CreateUser/>:tab==="usuarios"?<ManageUsers/>:tab==="etiquetas"?<TagsSettings/>:tab==="pipeline"?<StagesSettings/>:tab==="fila"?<QueueSettings/>:tab==="credenciais"&&profile?.role==="admin_master"?<Credentials/>:tab==="aparencia"&&profile?.role==="admin_master"?<Appearance/>:null}</section></div></>}
function CreateUser(){const {profile}=useAuth();const [form,setForm]=useState({name:"",email:"",password:"",phone:"",role:"consultor" as Role});const [msg,setMsg]=useState<{text:string;ok:boolean}|null>(null);const [busy,setBusy]=useState(false);
async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setMsg(null);try{await api("/users",{method:"POST",body:JSON.stringify(form)});setMsg({text:"Usuário criado e acesso liberado com sucesso.",ok:true});setForm({name:"",email:"",password:"",phone:"",role:"consultor"});}catch(e){setMsg({text:(e as Error).message,ok:false})}finally{setBusy(false)}}
return <div><div className="section-title"><i><UserCog/></i><div><h2>Criar novo usuário</h2><p>Cadastre um integrante e defina suas permissões.</p></div></div>{msg&&<div className={`alert ${msg.ok?"success":"error"}`}>{msg.text}</div>}<form className="form-grid" onSubmit={submit}><label>Nome completo<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Nome do colaborador" required/></label><label>E-mail<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="nome@empresa.com" required/></label><label>Senha provisória<input type="password" minLength={8} value={form.password} onChange={e=>setForm({...form,password:e.target.value})} placeholder="Mínimo 8 caracteres" required/></label><label>Telefone<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="(00) 00000-0000"/></label><label className="span-2">Cargo<select value={form.role} onChange={e=>setForm({...form,role:e.target.value as Role})}><option value="consultor">Consultor</option><option value="gestor">Gestor</option><option value="admin">Admin</option>{profile?.role==="admin_master"&&<option value="admin_master">Admin Master</option>}</select></label><div className="span-2 form-actions"><button className="primary" disabled={busy}>{busy?"Criando…":"Criar usuário"}</button></div></form></div>}
function ManageUsers(){const [users,setUsers]=useState<Profile[]>([]);const [error,setError]=useState("");const load=()=>api<Profile[]>("/users").then(setUsers).catch(e=>setError(e.message));useEffect(()=>{void load()},[]);
async function toggle(u:Profile){if(u.role==="admin_master")return;try{await api(`/users/${u.id}/status`,{method:"PATCH",body:JSON.stringify({status:u.status==="ativo"?"inativo":"ativo"})});await load()}catch(e){setError((e as Error).message)}}
return <div><div className="section-title"><i><Users/></i><div><h2>Gerenciar usuários</h2><p>Controle acessos e status da equipe.</p></div></div>{error&&<div className="alert error">{error}</div>}<div className="table-scroll"><table><thead><tr><th>Usuário</th><th>Cargo</th><th>Status</th><th>Ações</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td><b>{u.name}</b><small>{u.email}</small></td><td>{roleLabel[u.role]}</td><td><Badge tone={u.status==="ativo"?"green":"neutral"}>{u.status}</Badge></td><td><button className="link" onClick={()=>{const p=prompt("Nova senha provisória (mín. 8 caracteres):");if(p)void api(`/users/${u.id}/reset-password`,{method:"POST",body:JSON.stringify({password:p})}).then(()=>alert("Senha atualizada.")).catch(e=>setError(e.message))}}>Resetar senha</button><button className="link danger" disabled={u.role==="admin_master"} onClick={()=>toggle(u)}>{u.status==="ativo"?"Desativar":"Ativar"}</button></td></tr>)}</tbody></table></div></div>}
type AutomatedStage="agendado"|"orcamento_enviado"|"follow_up"|"matricula_feita"|"pagou"|"contrato_assinado"|"analise";
type TagItem={id:string;name:string;color:string;linked_stage:AutomatedStage|null};
const automatedStages:[AutomatedStage,string][]=[["agendado","Agendado"],["orcamento_enviado","Orçamento Enviado"],["follow_up","Follow-up"],["matricula_feita","Matrícula Feita"],["pagou","Pagou"],["contrato_assinado","Contrato Assinado"],["analise","Análise"]];
function StageLinkSelect({value,onChange}:{value:AutomatedStage|null;onChange:(value:AutomatedStage|null)=>void}){return <select value={value||""} onChange={e=>onChange((e.target.value||null) as AutomatedStage|null)}><option value="">Sem automação</option>{automatedStages.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select>}
function TagsSettings(){const [items,setItems]=useState<TagItem[]>([]);const [name,setName]=useState("");const [color,setColor]=useState("#d92f38");const [linkedStage,setLinkedStage]=useState<AutomatedStage|null>(null);const [error,setError]=useState("");const load=()=>api<TagItem[]>("/crm/tags").then(setItems).catch(e=>setError(e.message));useEffect(()=>{void load()},[]);
async function add(e:React.FormEvent){e.preventDefault();setError("");try{await api("/crm/tags",{method:"POST",body:JSON.stringify({name,color,linked_stage:linkedStage})});setName("");setLinkedStage(null);await load()}catch(e){setError((e as Error).message)}}
async function save(tag:TagItem){setError("");try{await api(`/crm/tags/${tag.id}`,{method:"PATCH",body:JSON.stringify({name:tag.name,color:tag.color,linked_stage:tag.linked_stage})});await load()}catch(e){setError((e as Error).message)}}
async function remove(id:string){if(!confirm("Excluir esta etiqueta e removê-la de todos os candidatos?"))return;setError("");try{await api(`/crm/tags/${id}`,{method:"DELETE"});await load()}catch(e){setError((e as Error).message)}}
const update=(id:string,changes:Partial<TagItem>)=>setItems(current=>current.map(tag=>tag.id===id?{...tag,...changes}:tag));
return <div><Section icon={<Tags/>} title="Etiquetas" text="Gerencie etiquetas globais e vincule etapas para mover candidatos automaticamente." />{error&&<div className="alert error">{error}</div>}<form className="tag-create" onSubmit={add}><label>Nome<input value={name} onChange={e=>setName(e.target.value)} placeholder="Ex.: Atendimento iniciado" required/></label><label>Etapa vinculada<StageLinkSelect value={linkedStage} onChange={setLinkedStage}/></label><label>Cor<input type="color" value={color} onChange={e=>setColor(e.target.value)}/></label><button className="primary"><Plus/>Adicionar</button></form><div className="tag-settings-list">{items.map(tag=><div key={tag.id}><input type="color" value={tag.color} onChange={e=>update(tag.id,{color:e.target.value})}/><input aria-label="Nome da etiqueta" value={tag.name} onChange={e=>update(tag.id,{name:e.target.value})}/><StageLinkSelect value={tag.linked_stage} onChange={linked_stage=>update(tag.id,{linked_stage})}/><button className="icon-button" title="Salvar etiqueta" onClick={()=>save(tag)}><Save/></button><button className="icon-danger" title="Excluir etiqueta" onClick={()=>remove(tag.id)}><Trash2/></button></div>)}</div></div>}

type Stage={id:string;stable_key:string;name:string;color:string;position:number};
function StagesSettings(){const {profile}=useAuth();const [items,setItems]=useState<Stage[]>([]);const [error,setError]=useState("");const locked=(s:Stage)=>["novos_leads","em_qualificacao","transferido"].includes(s.stable_key)&&profile?.role!=="admin_master";const load=()=>api<Stage[]>("/configuration/pipeline-stages").then(setItems).catch(e=>setError(e.message));useEffect(()=>{void load()},[]);
async function save(s:Stage){try{await api(`/configuration/pipeline-stages/${s.id}`,{method:"PATCH",body:JSON.stringify({name:s.name,color:s.color})});await load()}catch(e){setError((e as Error).message)}}async function remove(s:Stage){if(locked(s)||!confirm(`Excluir a etapa ${s.name}?`))return;try{await api(`/configuration/pipeline-stages/${s.id}`,{method:"DELETE"});await load()}catch(e){setError((e as Error).message)}}
return <div><Section icon={<Settings2/>} title="Etapas do pipeline" text="Personalize nomes e cores sem alterar a chave estável." />{error&&<div className="alert error">{error}</div>}<div className="stage-list">{items.map((s,i)=><div key={s.id}><span>{i+1}</span><input type="color" value={s.color} disabled={locked(s)} onChange={e=>setItems(x=>x.map(a=>a.id===s.id?{...a,color:e.target.value}:a))}/><input value={s.name} disabled={locked(s)} onChange={e=>setItems(x=>x.map(a=>a.id===s.id?{...a,name:e.target.value}:a))}/><code>{s.stable_key}</code>{locked(s)?<span className="locked"><Lock/>Protegida</span>:<><button className="icon-button" onClick={()=>save(s)}><Save/></button><button className="icon-danger" onClick={()=>remove(s)}><Trash2/></button></>}</div>)}</div></div>}

type Attendant={id:number;vendedor:string;telefone:string;atender:string;quantos_lead:number;ativo:boolean};
function QueueSettings(){const [queue,setQueue]=useState<{current:Attendant[];waiting:Attendant[]}>({current:[],waiting:[]});const [error,setError]=useState("");useEffect(()=>{api<any>("/configuration/queue").then(setQueue).catch(e=>setError(e.message))},[]);
const row=(a:Attendant)=><div className="queue-row" key={a.id}><span className="avatar">{a.vendedor?.slice(0,2).toUpperCase()}</span><div><b>{a.vendedor||"Sem nome"}</b><small>{a.telefone||"Sem telefone"}</small></div><strong>{a.quantos_lead||0}<small> leads</small></strong></div>;
return <div><Section icon={<Clock3/>} title="Fila de atendimento" text="Estado atual da distribuição automática de leads." />{error&&<div className="alert error">{error}</div>}<h4 className="eyebrow">CONSULTOR DA VEZ</h4><div className="queue-current">{queue.current.length?queue.current.map(row):<p>Nenhum consultor está marcado como “da vez”.</p>}</div><h4 className="eyebrow">EM ESPERA</h4><div className="settings-list queue">{queue.waiting.map(row)}</div></div>}

function Credentials(){const [data,setData]=useState<any>(null);const [token,setToken]=useState("");const [msg,setMsg]=useState("");const load=()=>api("/configuration/credentials").then(setData);useEffect(()=>{void load()},[]);
async function save(){try{const x=await api<any>("/configuration/credentials/uazapi",{method:"PUT",body:JSON.stringify({token})});setMsg(x.message);setToken("");await load()}catch(e){setMsg((e as Error).message)}}async function connect(){try{const x=await api<any>("/configuration/credentials/whatsapp/connect",{method:"POST"});setMsg(`WhatsApp: ${x.status}`);await load()}catch(e){setMsg((e as Error).message)}}
return <div><Section icon={<KeyRound/>} title="Credenciais e integrações" text="Segredos protegidos e disponíveis somente para Admin Master." />{msg&&<div className="alert success">{msg}</div>}<div className="credential-block"><h3>Supabase</h3><label>URL<input value={data?.supabaseUrl||"Carregando…"} readOnly/></label><label>Anon Key<input value={data?.supabaseAnonKey||"Carregando…"} readOnly/></label></div><div className="credential-block"><h3>Token uazapi</h3><div className="credential-line"><input type="password" value={token} onChange={e=>setToken(e.target.value)} placeholder={data?.tokenConfigured?"Token configurado ••••••••":"Cole o token da instância"}/><button className="primary" disabled={token.length<8} onClick={save}>Salvar token</button></div></div><div className="credential-block"><h3>WhatsApp</h3><div className="connection"><Wifi/><div><b>Status: {data?.whatsappStatus||"desconhecido"}</b><small>A conexão é realizada pelo backend.</small></div><button className="secondary" onClick={connect}>Conectar WhatsApp</button></div></div></div>}

function Appearance(){const [logo,setLogo]=useState<string|null>(null);const [colors,setColors]=useState({primary:"#d92f38",secondary:"#f05259",text:"#20232b",background:"#f5f6f8"});const [msg,setMsg]=useState("");useEffect(()=>{api<any>("/configuration/appearance").then(x=>{setLogo(x.logoUrl);setColors(x.colors)})},[]);
async function upload(file?:File){if(!file)return;const reader=new FileReader();reader.onload=async()=>{try{const x=await api<any>("/configuration/appearance/logo",{method:"POST",body:JSON.stringify({data:reader.result,contentType:file.type,extension:file.name.split(".").pop()?.toLowerCase()})});setLogo(x.logoUrl);setMsg("Logo atualizada com sucesso.")}catch(e){setMsg((e as Error).message)}};reader.readAsDataURL(file)}
async function saveColors(){try{await api("/configuration/appearance/colors",{method:"PUT",body:JSON.stringify(colors)});const root=document.documentElement;root.style.setProperty("--red",colors.primary);root.style.setProperty("--red2",colors.secondary);root.style.setProperty("--text",colors.text);root.style.setProperty("--page-bg",colors.background);setMsg("Cores aplicadas globalmente.")}catch(e){setMsg((e as Error).message)}}
return <div><Section icon={<Palette/>} title="Aparência" text="Personalize a identidade visual para todos os usuários." />{msg&&<div className="alert success">{msg}</div>}<div className="appearance-logo">{logo?<img src={logo} alt="Logo atual"/>:<div>Sem logo</div>}<label className="secondary upload"><Upload/>Enviar nova logo<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>upload(e.target.files?.[0])}/></label></div><div className="color-grid">{Object.entries({primary:"Cor primária",secondary:"Cor secundária",text:"Cor do texto",background:"Cor de fundo"}).map(([key,label])=><label key={key}>{label}<div><input type="color" value={colors[key as keyof typeof colors]} onChange={e=>setColors({...colors,[key]:e.target.value})}/><code>{colors[key as keyof typeof colors]}</code></div></label>)}</div><div className="form-actions"><button className="primary" onClick={saveColors}><Save/>Salvar cores</button></div></div>}

function Section({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <div className="section-title"><i>{icon}</i><div><h2>{title}</h2><p>{text}</p></div></div>}
